### PR TITLE
Should still try to save to remaining pools if it fails

### PR DESCRIPTION
**Pull request by cryptiklemur**

### CODE REVIEW

**Comment by Nyholm** [comment]
I do not understand this. This PR changes nothing, or am I missing something?

**Comment by cryptiklemur** [comment]
if $result is ever false (from a previous pool failing), it will (currently) short-circuit, and not save any of the following pools.

This fixes that.

**Comment by Nyholm** [comment]
Okey. You should write a comment and explain that. Also, write a test. Because this will be difficult to discover in the future if we forget it and update the code for some other reason. 

Good job!

**Comment by Nyholm** [comment]
You should also make this PR on the main repo. Sorry for not pointing it out earlier.

**Comment by cryptiklemur** [comment]
gah, crap.

**Pull request merged**
